version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./shared_files:/app/shared_files
      - ./users.db:/app/users.db
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - ENV=production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5173:5173"
    depends_on:
      - backend
    environment:
      - ENV=production

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    depends_on:
      - backend
      - frontend
    ports:
      - "8800:80"
